# -*- coding: utf-8 -*-
"""ML_task.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fQHKxS-noWnRTa8MADgNOftxHqXsSiDw
"""

import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeRegressor
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import plot_confusion_matrix
import seaborn as sns
import matplotlib as plt

heart_file="/heart.csv"
heart_data=pd.read_csv(heart_file)
heart_data.columns

y=heart_data.output
heart_features=['age','sex','cp','trtbps','chol','fbs','restecg','thalachh','exng','oldpeak','slp','caa','thall']
x=heart_data[heart_features]
train_x,val_x,train_y,val_y=train_test_split(x,y,random_state=0)
heart_model=LogisticRegression()
heart_model.fit(train_x,train_y)

train_data_prediction=heart_model.predict(train_x)
accuracy_train=accuracy_score(train_data_prediction,train_y)
print(accuracy_train)
train_data_prediction=heart_model.predict(val_x)
accuracy_val=accuracy_score(train_data_prediction,val_y)
print(accuracy_val)

input_array=(41,0,1,130,204,0,0,172,0,1.4,2,0,2)  # this is just random instance from the dataset given to check if its working
numpy_array=np.asarray(input_array)
new_numpy_array=numpy_array.reshape(1,-1)
prediction=heart_model.predict(new_numpy_array)
print(prediction)

plot_confusion_matrix(estimator=heart_model,X=val_x,y_true=val_y)

std_score=heart_model.score(val_x,val_y)
std_score

data={'age':[0],'sex':[0],'cp':[0],'trtbps':[0],'chol':[0],'fbs':[0],'restecg':[0],'thalachh':[0],'exng':[0],'oldpeak':[0],'slp':[0],'caa':[0],'thall':[0]}
feat_imp=pd.DataFrame(data)
feat_imp.head()

for i in heart_features:
  val_temp=val_x
  val_temp[i]=np.random.permutation(val_temp[i])
  print(val_temp.head())
  print(heart_model.score(val_temp,val_y))
  feat_imp[i]=std_score-heart_model.score(val_temp,val_y)

feat_imp.head()

# i found that the 3 most important features are restecg,chol,fbs because they created most variation in the prediction when changed .it was consistent among many trials which i did to train the model
#however i did not know how to plot the correspondence plot of the 3 features
# i did not understand what correlation between the 3 features mean although i tried googling it

import pickle
with open('pickle_file', 'wb') as files:
    pickle.dump(heart_model, files)

